name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Flutter App
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7'

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Build Flutter Web
        run: |
          flutter build web \
            --release \
            --base-href /contributor/ \
            --dart-define=APP_VERSION=${GITHUB_SHA::7}

      - name: Checkout Astro Pages Repository
        uses: actions/checkout@v4
        with:
          repository: cultural-arts/cultural-arts.github.io
          token: ${{ secrets.PAGES_REPO_TOKEN }}
          path: astro-site

      - name: Replace Contributor App
        run: |
          rm -rf astro-site/contributor
          mkdir -p astro-site/contributor

          cp -r build/web/* astro-site/contributor/

      - name: Commit and Push
        run: |
          cd astro-site

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add contributor

          git commit -m "Deploy contributor app ${GITHUB_SHA::7}" || echo "No changes"

          git push